name: publish

on: workflow_dispatch

jobs:
  publish:
    runs-on: "ubuntu-latest"
    env:
      NAME: circuit-railways
      FACTORIO_USER: ${{ secrets.FACTORIO_USER }}
      FACTORIO_PASSWORD: ${{ secrets.FACTORIO_PASSWORD }}

    steps:
      - uses: actions/checkout@master

      - name: Install
        run: |
          sudo apt-get install -y zip

      - name: Set version
        run: |
          echo "VERSION=$(sed -n 's/.*"version": *"\([^"]*\)".*/\1/p' info.json)" >> $GITHUB_ENV

      - name: Create archive
        run: |
          mkdir "${NAME}_${TAG}"
          cd "${NAME}_${TAG}"
          cp -r ../locale .
          cp ../*.{txt,lua,json} .
          cp ../thumbnail.png .
          rm utils.dev.lua
          mv utils.prod.lua utils.lua
          cd ../
          zip -r "${NAME}_${TAG}.zip" "./${NAME}_${TAG}"

      - name: Github Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: "${{ env.NAME }}_${{ env.VERSION }}.zip"
