name: publish

on: workflow_dispatch

env:
  BASE_FILE_NAME: circuit-railways

jobs:
  publish:
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@master

      - name: Install
        run: |
          sudo apt-get install -y zip

      - name: Set version
        run: |
          echo "PACKAGE_VERSION=$(sed -n 's/.*"version": *"\([^"]*\)".*/\1/p' info.json)" >> $GITHUB_ENV

      - name: Pack
        run: |
          mkdir release
          cd release
          cp -r ../locale .
          cp ../*.{txt,lua,json} .
          rm utils.dev.lua inspect.lua
          mv utils.prod.lua utils.lua
          zip -r "../$BASE_FILE_NAME_$PACKAGE_VERSION.zip" ./*
          cd ../

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.BASE_FILE_NAME }}_${{ env.PACKAGE_VERSION }}.zip
